services:
  data_processing_save_ids:
    build:
      context: .
      dockerfile: ./docker/1_Data_Processing_save_ids/Dockerfile
    volumes:
      - ./data:/data  # Mount the ./data folder from the host to /data in the container
    tty: true
    container_name: data_processing_save_ids
    environment:
      PYTHONUNBUFFERED: 1
      LANGUAGE: "de"

  data_processing_save_entities:
    build:
      context: .
      dockerfile: ./docker/2_Data_Processing_save_entities/Dockerfile
    volumes:
      - ./data:/data  # Mount the ./data folder from the host to /data in the container
    tty: true
    container_name: data_processing_save_entities
    environment:
      PYTHONUNBUFFERED: 1

  add_wikidata_to_astra:
    build:
      context: .
      dockerfile: ./docker/3_Add_Wikidata_to_AstraDB/Dockerfile
    volumes:
      - ./data:/data
    tty: true
    container_name: add_wikidata_to_astra
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      PYTHONUNBUFFERED: 1
      NVIDIA: "true"
      SAMPLE: "false"
      API_KEY: "datastax_wikidata_nvidia.json"
      BATCH_SIZE: 200
      OFFSET: 9160000
      COLLECTION_NAME: "qids_nvidia"

  run_retrieval:
    build:
      context: .
      dockerfile: ./docker/4_Run_Retrieval/Dockerfile
    volumes:
      - ./data:/data
    tty: true
    container_name: run_retrieval
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      PYTHONUNBUFFERED: 1
      JINA: "true"
      API_KEY: "datastax_wikidata_nvidia.json"
      COLLECTION_NAME: "wikidata_test_v1"
      BATCH_SIZE: 8
      EVALUATION_PATH: "LC_QuAD/processed_dataframe.pkl"
      # COMPARATIVE: "true"
      # COMPARATIVE_COLS: "Correct QID,Wrong QID"
      QUERY_COL: "Question"
      LANGUAGE: "en"
      ELASTICSEARCH_URL: "http://localhost:9200"
    network_mode: "host"