services:
  data_processing_save_labels_descriptions:
    build:
      context: .
      dockerfile: ./docker/1_Data_Processing_save_labels_descriptions/Dockerfile
    volumes:
      - ./data:/data  # Mount the ./data folder from the host to /data in the container
    tty: true
    container_name: data_processing_save_ids
    environment:
      PYTHONUNBUFFERED: 1
      LANGUAGE: "de"
      OFFSET: 0

  data_processing_save_items_per_lang:
    build:
      context: .
      dockerfile: ./docker/2_Data_Processing_save_items_per_lang/Dockerfile
    volumes:
      - ./data:/data  # Mount the ./data folder from the host to /data in the container
    tty: true
    container_name: data_processing_save_entities
    environment:
      PYTHONUNBUFFERED: 1

  add_wikidata_to_astra:
    build:
      context: .
      dockerfile: ./docker/3_Add_Wikidata_to_AstraDB/Dockerfile
    volumes:
      - ./data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    tty: true
    container_name: add_wikidata_to_astra
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      PYTHONUNBUFFERED: 1
      MODEL: "jina"
      SAMPLE: "true"
      API_KEY: "datastax_wikidata2.json"
      EMBED_BATCH_SIZE: 8
      QUERY_BATCH_SIZE: 100
      OFFSET: 120000
      COLLECTION_NAME: "wikidatav1"
      LANGUAGE: 'en'
      TEXTIFIER_LANGUAGE: 'en'
      ELASTICSEARCH_URL: "http://localhost:9200"
      ELASTICSEARCH: "false"
    network_mode: "host"

  run_retrieval:
    build:
      context: .
      dockerfile: ./docker/4_Run_Retrieval/Dockerfile
    volumes:
      - ./data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    tty: true
    container_name: run_retrieval
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      PYTHONUNBUFFERED: 1
      MODEL: "jina"
      API_KEY: "datastax_wikidata.json"
      COLLECTION_NAME: "wikidata_texttest"
      BATCH_SIZE: 100
      EVALUATION_PATH: "Mintaka/processed_dataframe.pkl"
      # COMPARATIVE: "true"
      # COMPARATIVE_COLS: "Correct QID,Wrong QID"
      QUERY_COL: "Question"
      QUERY_LANGUAGE: "en"
      # DB_LANGUAGE: "en"
      PREFIX: ""
    network_mode: "host"

  run_rerank:
    build:
      context: .
      dockerfile: ./docker/5_Run_Rerank/Dockerfile
    volumes:
      - ./data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    tty: true
    container_name: run_rank
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      PYTHONUNBUFFERED: 1
      MODEL: "jina"
      RETRIEVAL_FILENAME: "retrieval_results_Mintaka-wikidata_test_v1-en"
      BATCH_SIZE: 1
      QUERY_COL: "Question"
      LANGUAGE: "de"
    network_mode: "host"

  push_huggingface:
    build:
      context: .
      dockerfile: ./docker/6_Push_Huggingface/Dockerfile
    volumes:
      - ./data:/data
    tty: true
    container_name: push_huggingface
    environment:
      PYTHONUNBUFFERED: 1
      QUEUE_SIZE: 5000
      NUM_PROCESSES: 4
      SKIPLINES: 0
      ITERATION: 36

  create_prototype:
      build:
        context: .
        dockerfile: ./docker/7_Create_Prototype/Dockerfile
      volumes:
        - ./data:/data
        - ~/.cache/huggingface:/root/.cache/huggingface
      tty: true
      container_name: create_prototype
      environment:
        PYTHONUNBUFFERED: 1
        MODEL: "jinaapi"
        API_KEY: "datastax_wikidata.json"
        EMBED_BATCH_SIZE: 100
        NUM_PROCESSES: 16
        OFFSET: 0
        COLLECTION_NAME: "wikidata_prototype"
        LANGUAGE: 'en'
        TEXTIFIER_LANGUAGE: 'en'
        CHUNK_NUM: 5
      network_mode: "host"