services:
  data_processing_save_ids:
    build:
      context: .
      dockerfile: ./docker/1_Data_Processing_save_ids/Dockerfile
    volumes:
      - ./data:/data  # Mount the ./data folder from the host to /data in the container
    tty: true
    container_name: data_processing_save_ids
    environment:
      PYTHONUNBUFFERED: 1
      LANGUAGE: "de"
      OFFSET: 0

  data_processing_save_entities:
    build:
      context: .
      dockerfile: ./docker/2_Data_Processing_save_entities/Dockerfile
    volumes:
      - ./data:/data  # Mount the ./data folder from the host to /data in the container
    tty: true
    container_name: data_processing_save_entities
    environment:
      PYTHONUNBUFFERED: 1

  add_wikidata_to_astra:
    build:
      context: .
      dockerfile: ./docker/3_Add_Wikidata_to_AstraDB/Dockerfile
    volumes:
      - ./data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    tty: true
    container_name: add_wikidata_to_astra
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      PYTHONUNBUFFERED: 1
      MODEL: "jina"
      SAMPLE: "true"
      API_KEY: "datastax_wikidata_nvidia.json"
      EMBED_BATCH_SIZE: 8
      QUERY_BATCH_SIZE: 1000
      OFFSET: 2560000
      COLLECTION_NAME: "wikidata_test_v1"
      LANGUAGE: 'ar'

  run_retrieval:
    build:
      context: .
      dockerfile: ./docker/4_Run_Retrieval/Dockerfile
    volumes:
      - ./data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    tty: true
    container_name: run_retrieval
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      PYTHONUNBUFFERED: 1
      MODEL: "jina"
      API_KEY: "datastax_wikidata_nvidia.json"
      COLLECTION_NAME: "wikidata_langtest"
      BATCH_SIZE: 16
      EVALUATION_PATH: "REDFM/processed_dataframe_langtest.pkl"
      # COMPARATIVE: "true"
      # COMPARATIVE_COLS: "Correct QID,Wrong QID"
      QUERY_COL: "Sentence no entity"
      # QUERY_LANGUAGE: "ar"
      # DB_LANGUAGE: "en,ar"
      PREFIX: "_noentity"
      ELASTICSEARCH_URL: "http://localhost:9200"
    network_mode: "host"

  run_rerank:
    build:
      context: .
      dockerfile: ./docker/5_Run_Rerank/Dockerfile
    volumes:
      - ./data:/data
      - ~/.cache/huggingface:/root/.cache/huggingface
    tty: true
    container_name: run_rank
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      PYTHONUNBUFFERED: 1
      MODEL: "jina"
      RETRIEVAL_FILENAME: "retrieval_results_Mintaka-wikidata_test_v1-en"
      BATCH_SIZE: 1
      QUERY_COL: "Question"
      LANGUAGE: "de"
    network_mode: "host"